times = ('Palmeiras', 'Cruzeiro', 'Grêmio', 'Santos', 'Corinthians', 'Flamengo', 'Atlético Mineiro', 'Atlético Paranaense', 'Internacional', 'Chapecoense', 'Botafogo', 'São Paulo', 'Fluminense', 'Vasco da Gama', 'Bahia', 'Sport', 'Vitória', 'Ponte Preta', 'América', 'Coritiba')
print('-='*40)
print(f'Lista de times: {times}')
print('-='*40)
print(f'Os 5 primeiros são {times[:5]}')
print('-='*40)
print(f'Os 4 últimos são {times[-4:]}')
print('-='*40)
print(f'Times em ordem alfabética: {sorted(times)}')
print('-='*40)
print(f'O Chapecoense está na {times.index("Chapecoense")+1}º posição')
